version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=alumnos_db
      - POSTGRES_USER=Admin
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=alumnos@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
